layout_spectrum: 0.08378912
color:
  saturation: 0.6548111
  lightness: 0.4350111
  brandStrength: 0.4003055
  rhythmicContrast: 0.767629
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
typography_spectrum: 0.6361702
name: Finestkinddesigns
