typography_spectrum: 1
color:
  saturation: 0.6548111
  brandStrength: 0.4003055
  lightness: 0.4350111
  brandColors:
    - '#021727'
    - '#D7D191'
    - '#A3B488'
    - '#FDFCFC'
    - '#273938'
  rhythmicContrast: 0.767629
layout_spectrum: 1
name: TheFinestKindCo
navigation:
  - name: About
    id: 7ed5ab2b-1c33-41f5-9884-70da00cf08e7
    type: content
  - name: Shop the Finest Kind Co.
    url: 'http://thefinestkindco.com'
    type: external
  - name: Shop 163 Design Co.
    url: 'http://163designcompany.etsy.com'
    type: external
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: This Is The Finest Kind of Life
