layout_spectrum: 0.08378912
typography_spectrum: 0.6361702
color:
  saturation: 0.6548111
  lightness: 0.4350111
  brandStrength: 0.4003055
  brandColors:
    - '#322D28'
    - '#D8D7D2'
    - '#5C6542'
    - '#918877'
  rhythmicContrast: 0.767629
name: Finestkinddesigns
